// login/logout
export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
// club view
export const CLUB_GOT_LIST = 'CLUB_GOT_LIST';
export const CLUB_GOT_BY_ID = 'CLUB_GOT_BY_ID';
export const CLUB_GOT_MEMBERS = 'CLUB_GOT_MEMBERS';
export const CLUB_GOT_EVENTS = 'CLUB_GOT_EVENTS';
export const CLUB_CREATED = 'CLUB_CREATED';
export const CLUB_UPDATED = 'CLUB_UPDATED';
export const CLUB_DELETED = 'CLUB_DELETED';
export const CLUB_ERROR = 'CLUB_ERROR';
export const CLUB_CHANGE_SEARCH_FIELD = 'CLUB_CHANGE_SEARCH_FIELD';
export const CLUB_CHANGE_VIEW_MODE = 'CLUB_CHANGE_VIEW_MODE';
export const CLUB_SELECT_CLUB = 'CLUB_SELECT_CLUB';
export const CLUB_SELECT_CLUB_MEMBER = 'CLUB_SELECT_CLUB_MEMBER';
export const CLUB_SELECT_CLUB_EVENT = 'CLUB_SELECT_CLUB_EVENT';
// user view and logged in user details
export const USER_GOT_LIST = 'USER_GOT_LIST';
export const USER_GOT_CURRENT = 'USER_GOT_CURRENT';
export const USER_GOT_BY_ID = 'USER_GOT_BY_ID';
export const USER_GOT_EVENTS = 'USER_GOT_EVENTS';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_POSTED_IMAGE = 'USER_POSTED_IMAGE';
export const USER_CHANGED_PASSWORD = 'USER_CHANGED_PASSWORD';
export const USER_DELETED = 'USER_DELETED';
export const USER_DELETED_IMAGE = 'USER_DELETED_IMAGE';
export const USER_ERROR = 'USER_ERROR';
export const USER_CHANGE_SEARCH_FIELD = 'USER_CHANGE_SEARCH_FIELD';
export const USER_CHANGE_VIEW_MODE = 'USER_CHANGE_VIEW_MODE';
export const USER_CHANGE_VIEW_MODE_SELF = 'USER_CHANGE_VIEW_MODE_SELF';
export const USER_SELECT_USER = 'USER_SELECT_USER';
export const USER_SELECT_USER_EVENT = 'USER_SELECT_USER_EVENT';
// events view
