export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_GET_CURRENT = 'USER_GET_CURRENT';
export const USER_GET_BY_ID = 'USER_GET_BY_ID';
export const USER_GET_LIST = 'USER_GET_LIST';
export const USER_ERROR = 'USER_ERROR';
export const USER_CHANGE_SEARCH_FIELD = 'USER_CHANGE_SEARCH_FIELD';
export const USER_SELECT_USER = 'USER_SELECT_USER';
