export const countryOptions = [ // limited set of IOF member countries for now
  { value: 'AUS', label: 'AUS: Australia' },
  { value: 'AUT', label: 'AUT: Austria' },
  { value: 'BEL', label: 'BEL: Belgium' },
  { value: 'BUL', label: 'BUL: Bulgaria' },
  { value: 'CAN', label: 'CAN: Canada' },
  { value: 'CRO', label: 'CRO: Croatia' },
  { value: 'CZE', label: 'CZE: Czech Republic' },
  { value: 'DEN', label: 'DEN: Denmark' },
  { value: 'ESP', label: 'ESP: Spain' },
  { value: 'EST', label: 'EST: Estonia' },
  { value: 'FIN', label: 'FIN: Finland' },
  { value: 'FRA', label: 'FRA: France' },
  { value: 'GBR', label: 'GBR: Great Britain' },
  { value: 'GER', label: 'GER: Germany' },
  { value: 'HUN', label: 'HUN: Hungary' },
  { value: 'IRL', label: 'IRL: Ireland' },
  { value: 'ITA', label: 'ITA: Italy' },
  { value: 'LAT', label: 'LAT: Latvia' },
  { value: 'LTU', label: 'LTU: Lithuania' },
  { value: 'NED', label: 'NED: Netherlands' },
  { value: 'NOR', label: 'NOR: Norway' },
  { value: 'NZL', label: 'NZL: New Zealand' },
  { value: 'POL', label: 'POL: Poland' },
  { value: 'POR', label: 'POR: Portugal' },
  { value: 'ROU', label: 'ROU: Romania' },
  { value: 'RSA', label: 'RSA: South Africa' },
  { value: 'RUS', label: 'RUS: Russia' },
  { value: 'SRB', label: 'SRB: Serbia' },
  { value: 'SLO', label: 'SLO: Slovenia' },
  { value: 'SUI', label: 'SUI: Switzerland' },
  { value: 'SVK', label: 'SVK: Slovakia' },
  { value: 'SWE', label: 'SWE: Sweden' },
  { value: 'UKR', label: 'UKR: Ukraine' },
  { value: 'USA', label: 'USA: United States of America' },
];

export const roleOptions = [
  { value: 'admin', label: 'Administrator' },
  { value: 'guest', label: 'Guest' },
  { value: 'standard', label: 'Standard' },
];

export const visibilityOptions = [
  { value: 'public', label: 'public' },
  { value: 'all', label: 'all' },
  { value: 'club', label: 'club' },
  { value: 'private', label: 'private' },
];
